### ISSUE TITLE
Add contributing guide

### ISSUE THREAD

**Issue by vinayak-mehta** [vinayak-mehta/present#36]

**Comment by UdokaVrede** [comment]
hi @vinayak-mehta can i take this up?

**Comment by vinayak-mehta** [comment]
Yes!

I was thinking it along the lines of [this contributor's guide](https://camelot-py.readthedocs.io/en/master/dev/contributing.html). Though we can update it (since it hasn't been updated in a while) based on other good contributor's guides out there.

**Comment by vinayak-mehta** [comment]
The filing bug reports section should have this info: Operating system, terminal emulator name and version, Python version, and `present` version.

**Comment by vinayak-mehta** [comment]
Hey! I'm starting to work on this today, along with a GitHub issue template.
