### ISSUE TITLE
present stops immediately with "c = curses.tigetstr("sitm").decode("utf-8") #AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by johannboehme** [vinayak-mehta/present#54]
![image](https://user-images.githubusercontent.com/58803954/91701720-f870d080-eb77-11ea-8966-e5782a0038ff.png)

python version 3.7.3
WSL/Debian 10

**Comment by vinayak-mehta** [comment]
Already reported in #48. Thanks for reporting this, I'll push a quick fix to remove italics support for now, until it can be done in a cross-platform way in the future.

**Comment by johannboehme** [comment]
sorry! did read through the issue headers, but couldn't identify the existing one :)
Can't wait to finally try it, i was looking for a simpler pandoc presentation alternative for quite a while now

**Comment by vinayak-mehta** [comment]
No worries! I'll keep this open (as it has a better title) till I push a fix.

**Comment by vinayak-mehta** [comment]
This should be fixed with present v0.5.1, please reopen it if you still face the issue.
