### ISSUE TITLE
Tries to use python3.7 when python3.8 is installed

### ISSUE THREAD

**Issue by kiote99** [vinayak-mehta/present#55]
I have python 3.8.5 installed on macOS Mojave, it looks like present is trying to use the python 3.7 interpreter even though it isn't present.

```
➜  python --version
Python 3.8.5
➜  pip3 install present
Collecting present
  Using cached present-0.5.0-py3-none-any.whl (15 kB)
Requirement already satisfied: pyfiglet>=0.8.post1 in /usr/local/lib/python3.8/site-packages (from present) (0.8.post1)
Requirement already satisfied: PyYAML>=5.3.1 in /usr/local/lib/python3.7/site-packages (from present) (5.3.1)
Requirement already satisfied: asciimatics>=1.11.0 in /usr/local/lib/python3.8/site-packages (from present) (1.11.0)
Requirement already satisfied: Click>=7.0 in /usr/local/lib/python3.7/site-packages (from present) (7.1.1)
Requirement already satisfied: mistune>=2.0.0a4 in /usr/local/lib/python3.8/site-packages (from present) (2.0.0a4)
Requirement already satisfied: future in /usr/local/lib/python3.7/site-packages (from asciimatics>=1.11.0->present) (0.18.2)
Requirement already satisfied: Pillow>=2.7.0 in /usr/local/lib/python3.7/site-packages (from asciimatics>=1.11.0->present) (7.0.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/site-packages (from asciimatics>=1.11.0->present) (0.1.8)
Installing collected packages: present
Successfully installed present-0.5.0
➜  present sample.md
zsh: /usr/local/bin/present: bad interpreter: /usr/local/opt/python/bin/python3.7: no such file or directory
➜  ls /usr/local/opt/python/bin | grep python3
python3
python3-config
python3.8
python3.8-config
```

**Comment by kiote99** [comment]
Very excited to use this btw!  Totally understand if you are getting hugged to death from making the front page of hacker news https://news.ycombinator.com/item?id=24324099

**Comment by vinayak-mehta** [comment]
I had a totally different understanding of the `python_requires` key in setuptools. https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

Looks like you need to set every Python version you support? I guess I can just remove it and add `dataclasses` are a requirement for older Pythons.

**Comment by vinayak-mehta** [comment]
Oh I know why this is happening! `python_requires` works as expected but it was only added recently in 0.5.0. So when you install `present` using pip on earlier Pythons, it happens. Let me yank old versions from PyPI.

**Comment by vinayak-mehta** [comment]
@kiote99 Thanks for reporting this. As for the original issue, I think `python3.8 -m pip install present` should solve it. Please reopen this if you still face the same issue.
