### ISSUE TITLE
Image is not shown properly

### ISSUE THREAD

**Issue by macsir** [vinayak-mehta/present#73]
As my first testing, the sample pic is shown in this way? I am using Python 3.8.5
![image](https://user-images.githubusercontent.com/3345149/92043201-f6e51980-edbe-11ea-84d4-704ac4933bcb.png)

**Comment by macsir** [comment]
And other testing pictures can't be even shown at all.

**Comment by vinayak-mehta** [comment]
For images to be rendered nicely, you need to use a terminal emulator that supports more than 8 colors, or set your current one to use more than 8 colors. If you're using tmux, you can set it to support 256 colors using `set -g default-terminal "screen-256color"`.

**Comment by macsir** [comment]
Hi, Thanks. Is it possible to do it in Windows console?

**Comment by vinayak-mehta** [comment]
I was able to get nicer results with https://hyper.is/ on windows. I haven't tried the Windows console yet and don't have a Windows machine to test things :(
