### ISSUE TITLE
Back to school night present

### ISSUE THREAD

**Issue by rhelmstedter** [vinayak-mehta/present#75]
I made a presentation for back to school night for virtual learning. 

![BTSN_coding](https://user-images.githubusercontent.com/70656244/92179303-4ba58600-edf9-11ea-959b-00863740fc99.gif)

Below are the zipped files for the presentation and the codio.yml
[Archive.zip](https://github.com/vinayak-mehta/present/files/5171675/Archive.zip)

**Comment by vinayak-mehta** [comment]
This is awesome! Thanks for making it, I'll add it today. :smile:

**Comment by vinayak-mehta** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
