### ISSUE TITLE
Image paths aren't relative to presented markdown file

### ISSUE THREAD

**Issue by tmakowski** [vinayak-mehta/present#80]
**Describe the bug**
The paths provided in the images (and codio) inclusion statements `![](path/to/image)` are treated as relative to current working directory and not to the markdown file location.

**To Reproduce**
This won't work (see the screenshot below):
```sh
pip install present
git clone https://github.com/vinayak-mehta/present
cd present

present examples/sample.md
```

This will work just fine:
```sh
cd examples
present sample.md
```

**Expected behavior**
I would expect `present` to work without having to change directory first.

**Screenshots**
![image](https://user-images.githubusercontent.com/38053499/92305163-e4b4d800-ef84-11ea-8988-f0781d171ada.png)

**Environment**
 - OS: Ubuntu 20.04.1 LTS
 - Terminal emulator: [kitty](https://github.com/kovidgoyal/kitty)
 - Python version: 3.8.2
 - `present` version: 0.5.1

**Comment by vinayak-mehta** [comment]
Thanks for reporting this and opening a PR!
