### ISSUE TITLE
Using markdown comments throws NotImplementedError

### ISSUE THREAD

**Issue by tmakowski** [vinayak-mehta/present#82]
**Describe the bug**
Using markdown comment throws `NotImplementedError`. I suspect this is due to the `present` using these comments as part of it's syntax (for effects and coloring).

**To Reproduce**
Add a markdown comment (`<!-- comment text here -->`) to slides file.

**Expected behavior**
Either not throwing an `NotImplementedError` exception or throwing a more descriptive one (e.g. informing that comments not being supported).

**Slides**
```markdown
# Markdown Comments Test

Text before comment.

<!-- A markdown comment. -->

Text after comment.
```

**Environment**
 - OS: Ubuntu 20.04.1 LTS
 - Terminal emulator: [kitty](https://github.com/kovidgoyal/kitty)
 - Python version: 3.8.2
 - `present` version: 0.5.1

**Additional context**
A solution for this could be differentiating between a regular comment and `present` syntax. For example `<!-- effect=explosions -->` could be a regular comment and `<!-- [present] effect=explosions -->` could be `present` syntax.

**Comment by vinayak-mehta** [comment]
Thanks for reporting this!

**Comment by vinayak-mehta** [comment]
I think all comments can be skipped. Though the style will be applied if a comment has effects and colors in it.
