### ISSUE TITLE
Having two consecutive image inclusion lines causes NotImplementedError

### ISSUE THREAD

**Issue by tmakowski** [vinayak-mehta/present#83]
**Describe the bug**
Having two consecutive image inclusion lines (without a blank line in between) causes `NotImplementedError` to be raised.

**To Reproduce**
Add two image source lines. Example of slides below.

**Expected behavior**
An error informing that the image source lines should be separated by a blank line.

**Slides**
```markdown
# Good

![img](image.png)

![codio](codio.yaml)

---

# Bad

![img](image.png)
![codio](codio.yaml)

```

**Environment**
 - OS: Ubuntu 20.04.1 LTS
 - Terminal emulator: [kitty](https://github.com/kovidgoyal/kitty)
 - Python version: 3.8.2
 - `present` version: 0.5.1

**Additional context**
This is similar to #82 but I filed this separately because I would expect different errors from both. I also suspect that the root cause is different for both of these.

**Comment by vinayak-mehta** [comment]
Thanks for reporting this!
