### ISSUE TITLE
some kind of crash in current version

### ISSUE THREAD

**Issue by kanliot** [vinayak-mehta/present#86]
Some kind of crash.   just installed, but I can't get it to run. 

    $ present
    'Traceback (most recent call last):
      File "/usr/local/bin/present", line 6, in <module>
        from present.cli import cli
      File "/usr/local/lib/python2.7/dist-packages/present/cli.py", line 6, in <module>
        from .slideshow import Slideshow
      File "/usr/local/lib/python2.7/dist-packages/present/slideshow.py", line 105
        _effect = eval(f"_{slide.effect}")(self.screen)
                                        ^
    SyntaxError: invalid syntax

i also tried with a test.md file 

**Environment**
 - OS: [debian ]
 - Terminal emulator: [ guake]
 - Python version: [. 3.7.3]

**Additional context**
installed with sudo pip install present

**Comment by vinayak-mehta** [comment]
Please don't use `sudo pip install` as it can mess up your global Python. The recommended way to install Python packages is in a virtual environment. You can use https://github.com/pyenv/pyenv to install the Python version you want, and create a virtual env by following [this guide](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/).

Additionally, you need to pass the name of the markdown file for your slides when invoking present:

`$ present slides.md`

**Comment by kanliot** [comment]
I'll read that as you don't know how to create a pip package.  Thanks.

**Comment by vinayak-mehta** [comment]
I think you're getting a syntax error for the f-string because you're using a Python version less than 3.6.

> I'll read that as you don't know how to create a pip package. Thanks.

What would be the best way to create one? If you can give me some pointers, I can help solve your installation use-case better.
