### ISSUE TITLE
Support PageUp/Down for switching slides

### ISSUE THREAD

**Issue by GitSquared** [vinayak-mehta/present#88]
<img align="right" width="200px" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fs.sdgcdn.com%2F7%2F2018%2F06%2Fa17cb3470059569f9fc395de2ec8b37d0a4d855d_623175f6fdac4f04650e31c0cb9937e41bb3a70a_71e923Yy0kL._SL1500_-1-600x600.jpg&f=1&nofb=1" alt="A remote pres controller"/>

Most remote presentation controllers use PageUp and PageDown to trigger slide changes.

It should be easy to add support for those keys to switch slides in Present, and claim basic compatibility with those devices!

**Comment by vinayak-mehta** [comment]
That would be awesome, I'll look into it today! Just need to add the keys here: https://github.com/vinayak-mehta/present/blob/master/present/slideshow.py#L44

**Comment by GitSquared** [comment]
Tried to hack it together myself (I have 0 experience in python), but it doesn't work, not sure why.

```diff
diff --git a/present/slideshow.py b/present/slideshow.py
index dd75c5a..70fafcf 100644
--- a/present/slideshow.py
+++ b/present/slideshow.py
@@ -43,7 +43,7 @@ class Slide(Scene):
             c = event.key_code
             if c == ord("r"):
                 self._reset()
-            elif c in (ord("b"), Screen.KEY_LEFT):
+            elif c in (ord("b"), Screen.KEY_LEFT, Screen.KEY_PAGE_UP):
                 self.show.current_slide -= 1
 
                 try:
@@ -57,7 +57,7 @@ class Slide(Scene):
                     )
                 except IndexError:
                     pass
-            elif c in (ord(" "), ord("n"), Screen.KEY_RIGHT):
+            elif c in (ord(" "), ord("n"), Screen.KEY_RIGHT, Screen.KEY_PAGE_DOWN):
                 self.show.current_slide += 1
 
                 try:
```

```
> python setup.py build
> python build/lib/present/__main__.py ~/Desktop/pres.md
```

If you have any explanation, I'd be willing to learn... 😄

**Comment by vinayak-mehta** [comment]
Oh let me try and run this patch later in the day, I'm not sure if `Screen.KEY_PAGE_DOWN` is supported by asciimatics, on which `present` is built on.

**Comment by GitSquared** [comment]
Found it through my IDE's autocompletion, so I figure the code itself should be okay, but I'm not 100% sure.
Anyway, I'll let you try.

**Comment by vinayak-mehta** [comment]
So I just tried this and it works! I follow this development workflow:

1. Install in editable mode `pip install -e .` in a virtual environment
2. Make changes
3. Run normally using `present slides.md`

I followed your `setup.py build` workflow and it worked with that too. What OS are you on? Maybe this is an OS-specific issue?

**Comment by vinayak-mehta** [comment]
Btw you can also raise a PR to add this if you have time today! :)

**Comment by GitSquared** [comment]
> I followed your setup.py build workflow and it worked with that too. What OS are you on? Maybe this is an OS-specific issue?

Linux (arch), with the `fish` shell. I figure there must be some kind of conflict between the version of present I installed globally and the one I'm trying to test. Oh well, as long as it works on your end!

Thanks for looking into this. Created a PR at #90.

**Comment by vinayak-mehta** [comment]
> I figure there must be some kind of conflict between the version of present I installed globally and the one I'm trying to test. Oh well, as long as it works on your end!

Hmm, can you try installing the project in a new [virtual environment](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/) and then test again? If you still the face the problem, please open another issue for the bug.

**Comment by vinayak-mehta** [comment]
Thanks for raising the PR!
