### ISSUE TITLE
Trustless Bridges Presentation

### ISSUE THREAD

**Issue by HCastano** [vinayak-mehta/present#91]
Hi! I recently made a presentation using `present` and figured it would be nice to get it added to the gallery. The presentation is about trustless blockchain bridges built using the [Substrate](https://github.com/paritytech/substrate) blockchain building framework. Bridges are a way to connect different blockchains without a trusted central party. The slides can be found [here](https://github.com/HCastano/trustless-bridges-presentation).

I had a lot of fun making the slides with `present` - will definitely be using it again in the future!

![Screen-Recording-2020-09-08-at-8](https://user-images.githubusercontent.com/12344623/92541466-14c5da80-f214-11ea-936c-d8f29506dd62.gif)

**Comment by vinayak-mehta** [comment]
This looks great! Thanks for using present :)

Looks like you bumped into #10, I'll try to work on a fix soon.

**Comment by vinayak-mehta** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by vinayak-mehta** [comment]
@HCastano Btw, how did you generate the bridge ASCII art? It looks beautiful!

**Comment by HCastano** [comment]
> @HCastano Btw, how did you generate the bridge ASCII art? It looks beautiful!

I snagged it from [here](https://www.asciiart.eu/buildings-and-places/bridges). Credit goes to someone by the name of Joan Stark. All the other diagrams were made with [Asciiflow Infiniti](http://asciiflow.com/).

**Comment by vinayak-mehta** [comment]
Thanks for posting the links! I'm going to totally use asciiart from here in future presentations :smile:
